### ISSUE TITLE
Jest: `TypeError: Cannot read property 'registerLocale' of undefined`

### ISSUE THREAD

**Issue by asode** [michaelwittig/node-i18n-iso-countries#279]
Hi, I was wondering what am I doing wrong here as I'm trying to test my component with `jest`. In browser it works fine. Should I somehow exclude the language imports from `jest` run as it doesn't run in a browser (just speculating)?
```
node 14.17.3
npm 8.5.0
```
```
i18n-iso-countries@7.3.0
jest@27.5.1
@testing-library/dom@8.11.3
@testing-library/jest-dom@5.16.2
@testing-library/svelte@3.0.3
@testing-library/user-event@13.5.0
```

<details><summary>import countries from "i18n-iso-countries"</summary>
<p>

```js
  // Register.svelte
  import countries from "i18n-iso-countries";
  import countriesEnglish from "i18n-iso-countries/langs/en.json";
  countries.registerLocale(countriesEnglish);
```

Jest outputs the following error:

```js
TypeError: Cannot read property 'registerLocale' of undefined

      13 |   import countriesEnglish from "i18n-iso-countries/langs/en.json";
    > 14 |   countries.registerLocale(countriesEnglish);
         |             ^

      at instance (src/components/register/Register.svelte:14:13)
      at init (node_modules/svelte/internal/index.js:1865:11)
      at new Register (src/components/register/Register.svelte:604:3)
      at render (node_modules/@testing-library/svelte/dist/pure.js:81:21)
      at Object.<anonymous> (src/components/register/Register.test.ts:145:11)
```
</p>
</details>

---

Also tried `import *` (inspired by #125), but it only caused a different error:

<details><summary>import * as countries from "i18n-iso-countries"</summary>
<p>

```js
  // Register.svelte
  import * as countries from "i18n-iso-countries";
  import countriesEnglish from "i18n-iso-countries/langs/en.json";
  countries.registerLocale(countriesEnglish);
```

Jest outputs the following error:

```js
TypeError: Cannot read property 'locale' of undefined

      13 |   import countriesEnglish from "i18n-iso-countries/langs/en.json";
    > 14 |   countries.registerLocale(countriesEnglish);
         |             ^

      at Object.<anonymous>.exports.registerLocale (node_modules/i18n-iso-countries/index.js:99:19)
      at instance (src/components/register/Register.svelte:14:13)
      at init (node_modules/svelte/internal/index.js:1865:11)
      at new Register (src/components/register/Register.svelte:607:3)
      at render (node_modules/@testing-library/svelte/dist/pure.js:81:21)
      at Object.<anonymous> (src/components/register/Register.test.ts:145:11)
```
</p>
</details>

**Comment by Gurochka** [comment]
Another solution is to add a root path to the jest.config.js file:
` roots: ["<rootDir>/src", "<rootDir>/node_modules/i18n-iso-countries"].`
 That worked for me.
