### ISSUE TITLE
Error: Cannot find module './codes.json'

### ISSUE THREAD

**Issue by gerwinbrunner** [michaelwittig/node-i18n-iso-countries#39]
I just installed `i18n-iso-countries `
and get thee following error:

```
W20170129-12:30:52.372(1)? (STDERR) Error: Cannot find module './codes.json'
W20170129-12:30:52.373(1)? (STDERR)     at require (packages/modules-runtime.js:114:19)
W20170129-12:30:52.373(1)? (STDERR)     at meteorInstall.node_modules.i18n-iso-countries.index.js (packages/modules.js:1207:13)
W20170129-12:30:52.373(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170129-12:30:52.373(1)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)
W20170129-12:30:52.373(1)? (STDERR)     at Module.Mp.import (/Users/ap/.meteor/packages/modules/.0.7.7.iu0idl++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170129-12:30:52.373(1)? (STDERR)     at meteorInstall.imports.api.jotForm.server.worker.js (imports/api/jotForm/server/worker.js:1:1)
W20170129-12:30:52.373(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170129-12:30:52.374(1)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)
W20170129-12:30:52.374(1)? (STDERR)     at Module.Mp.import (/Users/ap/.meteor/packages/modules/.0.7.7.iu0idl++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170129-12:30:52.374(1)? (STDERR)     at meteorInstall.imports.api.jotForm.server.publications.js (imports/api/jotForm/server/publications.js:1:1)
W20170129-12:30:52.374(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170129-12:30:52.374(1)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)
W20170129-12:30:52.374(1)? (STDERR)     at Module.Mp.import (/Users/ap/.meteor/packages/modules/.0.7.7.iu0idl++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170129-12:30:52.375(1)? (STDERR)     at meteorInstall.imports.startup.server.register-api.js (imports/startup/server/register-api.js:1:1)
W20170129-12:30:52.375(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170129-12:30:52.375(1)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)
W20170129-12:30:52.375(1)? (STDERR)     at Module.Mp.import (/Users/ap/.meteor/packages/modules/.0.7.7.iu0idl++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170129-12:30:52.375(1)? (STDERR)     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:1:13)
W20170129-12:30:52.375(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170129-12:30:52.375(1)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)
W20170129-12:30:52.375(1)? (STDERR)     at Module.Mp.import (/Users/ap/.meteor/packages/modules/.0.7.7.iu0idl++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170129-12:30:52.376(1)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:1)

```

**Comment by gerwinbrunner** [comment]
Seemed to be an installation issue on my end.
After whipping the node_modules folder it worked.
